pagopa/pagopa-payment-transactions-gateway

- .devops/azure-pipelines-build-deploy-SIT.yml
> PM-459: fix "Get Branch Version"

- .devops/azure-pipelines-build-deploy-SIT.yml
> PM-459: removed dependencies for s4s

- .devops/azure-pipelines-build-deploy-SIT.yml
fix SonarCloud
https://pagopa.atlassian.net/browse/PM-459
> PM-459: fix SonarCloud

- src/main/java/it/pagopa/pm/gateway/utils/ClientUtil.java
- src/main/java/lombok.config
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/ControllerTests.java
Added verify check and lombok.configuration file
> Pm 561 b pay junit test

- .devops/azure-pipelines-build-deploy-SIT.yml
fix code coverage
https://pagopa.atlassian.net/browse/PM-459
> PM-459: fix code coverage

- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/ControllerTests.java
> PM-561 fixed test

- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
Added default timeout value and catch of numberformatexception
> Added default value for timeout and catch of NumberFormat Exception

- pom.xml
- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
Changed way timeout is set in message sender
> Pm 558 handling bpay refunds

- .devops/azure-pipelines-deploy-UAT-PROD.yml
- .devops/templates/check-files.yml
- .devops/templates/verify-branch-version.yml
added check-files.yml and verify-branch-version.yml
https://pagopa.atlassian.net/browse/PM-468
> PM-468: added check-files.yml and verify-branch-version.yml

- src/main/java/it/pagopa/pm/gateway/client/bpay/BancomatPayClient.java
- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
- src/main/java/it/pagopa/pm/gateway/config/SessionListener.java
- src/main/java/it/pagopa/pm/gateway/constant/SessionParams.java
- src/main/java/it/pagopa/pm/gateway/controller/PaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/BPayRefundRequest.java
Handling BPay payments where callback didn't arrive in time
> Pm 638 handling bpay auth timeout

- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
- src/main/java/it/pagopa/pm/gateway/config/SessionListener.java
- src/main/java/it/pagopa/pm/gateway/controller/PaymentTransactionsController.java
> Added timeout default value

- pom.xml
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
- src/main/java/it/pagopa/pm/gateway/config/SessionListener.java
- src/main/java/it/pagopa/pm/gateway/controller/HealthCheckController.java
> PM-671 - Replacing Log4j with Slf4j

- src/main/java/it/pagopa/pm/gateway/controller/PaymentTransactionsController.java
> PM-638 - Fix session

- src/main/java/it/pagopa/pm/gateway/config/SessionListener.java
- src/main/java/it/pagopa/pm/gateway/controller/PaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/entity/BPayPaymentResponseEntity.java
> PM-638 - Fix NPEs

- src/main/java/it/pagopa/pm/gateway/controller/PaymentTransactionsController.java
> PM-638 - Handling KO outcome in refund response

- pom.xml
- src/main/java/it/pagopa/pm/gateway/client/bpay/BancomatPayClient.java
> PM-638 - Logging requests to BPay

- src/main/java/it/pagopa/pm/gateway/client/bpay/BancomatPayClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
- src/main/java/it/pagopa/pm/gateway/constant/Headers.java
- src/main/java/it/pagopa/pm/gateway/controller/PaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/entity/BPayPaymentResponseEntity.java
- src/main/java/it/pagopa/pm/gateway/utils/ClientUtils.java
- src/main/java/it/pagopa/pm/gateway/utils/MdcUtils.java
Adding MDC values to BPay payment flow logs.
Need to monitor BPay payment flows in full using MDC values (especially Request IDs).
Mocked calls.
> Pm 687 mdc info in pgs logs

- api-specs/spec_Bpay.yaml
> PM-733 - Swagger update

- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/ControllerTests.java
> PM_754 Junit Test storno / inquiry BPAY

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
> PM-740 - Little Fixes, Added Error Field into Entity

- src/main/java/it/pagopa/pm/gateway/client/azure/AzureLoginClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
- src/main/java/it/pagopa/pm/gateway/constant/Messages.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
Modified logic 
- [] New feature (non-breaking change which adds functionality)
> Pm 739/740 fixes branch

- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
Added Junit Tests to increase code coverage on PostePayPaymentController
> Pm 844 v2 poste pay junit tests

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
Fixed urlRedirect e clientResponseUrl setting in GET response.
Also changed HTTP status from 500 to 401 accordingly to design review when a transaction has already been processed previously
> PM-866/867 redirectUrl e responseUrl fixed

- .devops/templates/clean_and_download.yml
> Liquibase - added missing templates

- .devops/templates/clean_and_download.yml
> Liquibase - removed typo

- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
The changes in this PR are required in order to use a proxy when calls towards the APIM of PagoPA are performed.
These specific changes should allow to call PostePay /createPayment API via the APIM.
A proxy is attached to the ApiClient whenever it is required.
Tests in local environment have been done.
> PM-890 - added proxy into ApiClient creation logic

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
Added logs when receiving an API exception from PostePay's createPayment request.
Now logging: 
- httpStatus (separatly to make it clear at first sight)
- responseBody (separatly to make it clear at first sight)
- complete exception (for further analysis)
> [improvement] - added logs when receiving an API exception from PostePay

- src/main/java/it/pagopa/pm/gateway/constant/ClientConfigs.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/resources/swagger/spec_PostePay.yaml
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
With this pull request, a problem within the request towards PostePay's createPayment has been solved.
There was a missing parameter **merchantId** into PostePay's swagger which was not included among the client's auto-generated request parameters.
merchantId parameter has been added to the request object for the createPayment primitive defined into PostePay's swagger.
Request object in code has been integrated with the new parameter and it has also been added into configuration among the others (shopId, etc.).
Junit tests have been integrated as well.
This change is required since the current request object definition for createPayment API does not include the merchantId parameter, so the call to PostePay is not succesful.
This fix has been tested in local environment, but should be …
> PM-902 postepay swagger fixes for merchantid

- devops/db/liquibase/run_image.sh
> Set custom name for changelog table for local docker dev environment

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/resources/swagger/spec_PostePay.yaml
This development was required since PostePay's swagger is incomplete and incorrect.
The refund API was using the request body for /details API, so the auto-generated client was incorrect resulting in an unsuccessful call to the API.
The changes in this PR consist in:
- correcting the swagger definition
- correcting the code in order to use the right request body 
This development has been primarily tested by calling directly PostePay and guessing the correct request body to use, then by developing the code afterwards.
This would be tested in SIT environment and also with the mock-psp application, as soon as it will be developed.
https://pagopa.atlassian.net/browse/PM-860
> PM-895 - Changed refund API implementation 

- .devops/azure-pipelines-deploy-UAT-PROD.yml
> Commented Liquibase stage

- .devops/azure-pipelines-deploy-UAT-PROD.yml
> Commented Liquibase stage UAT

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayPollingResponse.java
- src/main/java/it/pagopa/pm/gateway/dto/enums/StatusErrorCodeOutcomeEnum.java
**Adding a payment-request status**
Created StatusErrorCodeOutcomeEnum,.
Added a new field to the response of the GET request-payments / postepay (statusErrorCodeOutcome)
This field is used to help the PM to choose the correct logout webview to show to the user.
- [x ] New feature (non-breaking change which adds functionality)
https://pagopa.atlassian.net/browse/PM-900
> Pm 900 status payment request

- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
> Pm-913-v2 added log to client config

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
1. Removed statusErrorCode when authorization from PostePay has not yet arrived.
2. Taken and returned the property PGS_CLIENT_RESPONSE_URL_ONBOARDING in the onboarding' case
1. In this case satusErrorCode must not be shown
2. It is used to return the correct webview
> PM-900-v2 

- src/main/java/it/pagopa/pm/gateway/constant/LogoPaths.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
Moved postepay logo retrieval logic into standalone
Moved postepay logo retrieval logic into standalone
> Moved postepay logo retrieval logic into standalone

- src/main/java/it/pagopa/pm/gateway/constant/Scopes.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
Added scope parameter to urlRedirect property in order to identify the client scope (in this case, postepay)
Added scope parameter and changed property value on standalone.xml file
> PM-927 - changed urlRedirect property according to specifications

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayPollingResponse.java
Added onboarding filed to GET Response
> PM-926 added onboarding to GET rsponse

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayAuthResponse.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayPollingResponse.java
Added requestId to POST /request-payments/postepay response
Set requestId value in the response as PaymentRequestEntity guid
Changed field name from guid to responseId in GET /request-payments/postepay/{requestId} response
Added control of onboarding case in calling closePayment() in PUT request-payments/postepay
> PM-932 fix onboarding

- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
> PM-932 fix tests after onboarding modifications

- api-specs/api_spec_PGS.yaml
- add `requestId` in `PostePayAuthResponseEntity`.
> Update api spec with requestId

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
- src/main/java/it/pagopa/pm/gateway/constant/Params.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
This PR is needed in order to save on table PP_PGS_REQUEST_INFO the IS_ONBOARDING parameter correctly and avoid null values.
A null value in this column does not trigger the call to the PATCH API, thus to closePaymentV2 because each transaction is considered as an onboarding
> PM-909 - fix for PATCH call

- .devops/azure-pipelines-deploy-PT.yml
- .devops/templates/prod/upgrade_db.yml
- .devops/templates/uat/upgrade_db.yml
Liquibase - Fixed ResourceGroupName
> Liquibase - fixed ResourceGroupName

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayPatchRequest.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayPatchRequestData.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/BancomatPayControllerTests.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
This PR is needed since the old implementation was not compliant to the design review.
The call to the PATCH API on PM has been reworked so a request body is passed and, more important, the correct transaction status is passed to the Payment Manager in order to set the correct status and proceed with the call to closePayment V2
- new parameter status for the transaction passed to PM
- request body instead of query parameters
https://pagopa.atlassian.net/browse/PM-909
> PM-909 - fix for PUT API logic

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/controller/BancomatPayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/BPayOutcomeResponse.java
Adding explicit outcome response bodies to BPay payment and refund calls.
Handle "fake" 2xx codes from APIM in the event of mapping errors in calls to PGS.
> Pm 937 handling 2xx bpay pgs error responses

- .devops/templates/pt/upgrade_db.yml
> fixex export path

- src/main/java/it/pagopa/pm/gateway/controller/BancomatPayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/enums/TransactionStatusEnum.java
> PM-940 - Changing enum name

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayAuthResponse.java
Added a new valure (correlation-id) to the POST /request-payments/postepay response.
https://pagopa.atlassian.net/browse/PM-960
> PM-960 Added a new value to the POST response

- src/main/java/it/pagopa/pm/gateway/config/ClientConfig.java
- src/main/java/it/pagopa/pm/gateway/constant/ApiPaths.java
- src/main/java/it/pagopa/pm/gateway/constant/Params.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/PostePayOnboardingRequest.java
- src/main/resources/swagger/spec_PostePay.yaml
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
Fixed PostePayOnboarding.
Swagger updated.
Added an api on the pgs to execute onboarding (.../request-payment /postepay/onboarding).
The postepay onboarding API (.../api/v1/user/) is called with the updated and correct body.
This change needed after receiving the updated swagger.
https://pagopa.atlassian.net/browse/PM-971
> PM-971 Fixed PostePay Onboarding

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/constant/Params.java
- src/main/java/it/pagopa/pm/gateway/controller/BancomatPayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/TransactionUpdateRequest.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
Replacing API with new field in PP_TRANSACTION
> PM-669 - Removing API

- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
Implemented JUnit tests for PostePay onboarding
https://pagopa.atlassian.net/browse/PM-974
> PM-974 Test jUnit PostePay Onboarding

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClient.java
PATCH endpoint changed as requested - update-status has been removed in path
> fixed patch endpoint as requested

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
Added api key authentication to headers for PATCH
> PM-977 - Added api key authentication to headers for PATCH

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
> Added api key authentication to headers for PATCH

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
Fixed clientResponseUrl for PostePay Payment
https://pagopa.atlassian.net/browse/PM-976
> PM-976 Fixed clientResponseUrl PostePay

- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/resources/application.properties
> test fixes

- README.md
> PM-889 Readme

- .devops/azure-pipelines-deploy-UAT-PROD.yml
Enable liquibase stage in UAT pipeline
> Enable liquibase stage in UAT pipeline

- .env.local
> fix(env): fix `.env.local`

- src/main/java/it/pagopa/pm/gateway/service/XpayService.java
- src/main/resources/application.properties
Added "Ocp-Apim-Subscription-Key" to the headers of the API
> PM-1100 FIX callAutenticazione3DS

- src/main/java/it/pagopa/pm/gateway/service/XpayService.java
Added new log.info to show the request
> PM-1100 add log.info

- api-specs/api_spec_PGS.yaml
* change type `integer` -> `string` for `PostePayAuthRequest.idTransaction` field
Spec was not consistent with [PostePayAuthRequest entity definition](https://github.com/pagopa/pagopa-payment-transactions-gateway/blob/39dc19fd201916cbda9e53732437818004b1a919/src/main/java/it/pagopa/pm/gateway/dto/PostePayAuthRequest.java#L13-L14)
> fix(api-spec): change type `integer` -> `string` for `PostePayAuthRequest.idTransaction` field

- api-specs/api_spec_PGS.yaml
Added request-payments/xpay/{requestId{/resume into ApiSpec
> Pm 1144 api spec x pay

- .db/postgres/changes/changelog.xml
- .devops/code-review-pipelines.yml
- .env.local
> feat: Add healtcheck in code review pipeline

- api-specs/api_spec_PGS.yaml
ApiSpec updated with new API for xpay
- [x ] I have updated the documentation accordingly.
https://pagopa.atlassian.net/browse/PM-1144
> PM-1144 apiSpec XPAy

- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClient.java
- src/main/java/it/pagopa/pm/gateway/client/restapicd/RestapiCdClientImpl.java
- src/main/java/it/pagopa/pm/gateway/constant/XPayParams.java
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/PatchRequestData.java
- src/main/java/it/pagopa/pm/gateway/dto/XPay3DSResponse.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
…{requestId}/resume
POST call updated to a GET call. 
[GET] request-payments/xpay/{requestId}/resume.
requestBody changed in a map as a parameter.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have updated the documentation accordingly.
(https://pagopa.atlassian.net/browse/PM-1132)
> PM-1132 POST call updated to a GET call 

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/XPayPollingResponse.java
Added requestId into GET polling response
- [ x] I have updated the documentation accordingly.
(https://pagopa.atlassian.net/browse/PM-1171)
> PM-1171 Added requestId into GET polling response

- src/main/java/it/pagopa/pm/gateway/controller/BancomatPayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/dto/TransactionUpdateRequest.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
This PR has been opened since it is needed to add parameter correlationId in request to closePayment API, this to proceed with sendPaymentResult/notificationService flow.
- new parameter correlationId (RRN on PM) passed in request body to PM's PATCH
- tests have been changed as well to manage the new parameter
https://pagopa.atlassian.net/jira/software/c/projects/PM/boards/105?selectedIssue=PM-1184
> PM-1184 - added correlationId in PATCH request to PM

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/xpay/XPayAuthResponse.java
- src/main/java/it/pagopa/pm/gateway/utils/XPayUtils.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
Fixed mac generation.
- [x ] I have updated the documentation accordingly.
https://pagopa.atlassian.net/browse/PM-1195
> PM-1195 Fixed mac generation

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/utils/XPayUtils.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
The resume API always returns 302 even if `paga3ds` returns `KO`, even if the input values are incorrect and even if an error occurs after the `paga3ds`.
- [x ] I have updated the documentation accordingly.
https://pagopa.atlassian.net/browse/PM-1201
https://pagopa.atlassian.net/browse/PM-1202
https://pagopa.atlassian.net/browse/PM-1204
> PM-1202 fixed resume

- .devops/azure-pipelines-deploy-PROD.yml
- .devops/templates/prod/upgrade_db.yml
Change of service connection name in deploy pipeline for production env
> change service connection name

- devops/db/liquibase/changelogs/payment-transaction-gateway/incremental-changelogs/V5_PM_988-changelog.xml
- devops/db/liquibase/changelogs/payment-transaction-gateway/incremental-changelogs/V6_PM_1102-changelog.xml
changed "incremental" to "incremental-uat" for DDL scripts that need to be executed in UAT environment
https://pagopa.atlassian.net/browse/PM-1176
> PM-1176 - UAT release preparation

- devops/db/liquibase/changelogs/payment-transaction-gateway/incremental-changelogs/V6_PM_1102-changelog.xml
added "incremental-uat, pt and prod" for DDL scripts that need to be executed in UAT, perfomance and production environment
> PM-1176 - liquibase fixes

- devops/db/liquibase/changelogs/payment-transaction-gateway/incremental-changelogs/V5_PM_988-changelog.xml
- devops/db/liquibase/changelogs/payment-transaction-gateway/incremental-changelogs/V6_PM_1102-changelog.xml
Context "incremental-uat" has been added in changelog files so each script which has not been executed in UAT environment will be executed in the next UAT pipeline execution.
Context "incremental-prod" has been intentionally skipped since a new branch will be created in order to add the whole table in production environment.
- liquibase changelog.xml changed
This fix will add columns which have not been added last time in UAT environment
> PM-1176 - added "incremental-uat" context in liquibase changelog files

- .github/PULL_REQUEST_TEMPLATE.md
* Update GitHub PR template checklist
Added a few points on PR size, DB schema changes and API spec changes
> refactor(github): update PR template checklist

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/xpay/XPayReport.java
- src/main/java/it/pagopa/pm/gateway/utils/XPayUtils.java
> Fixed XPay problems

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/dto/vpos/CcPaymentInfoResponse.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
> PM-1263 Fix costruzione VposUrl

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/constant/ApiPaths.java
- src/main/java/it/pagopa/pm/gateway/constant/VposConstant.java
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/creditcard/CreditCardResumeRequest.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/MethodCompletedEnum.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeService.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VPosRequestUtilsTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VPosUtilsTest.java
Added new API: `/request-paymets/creditCard/{requestId}/resume`.
Created Logic to manage Step-1.
Updated Api-Spec.
Updated UnitTest
https://pagopa.atlassian.net/browse/PM-1225
> PM-1225 Step1

- src/test/java/it/pagopa/pm/gateway/service/CcPaymentInfoServiceTest.java
> Fix CcPaymentInfoServiceTest

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/dto/creditcard/StepZeroRequest.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosUtils.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/utils/VPosRequestUtilsTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VPosUtilsTest.java
Removed `reqRefNumber` from request body of POST `request-payments/creditCard`.
Created logic to retrieve the reqRefNum
- [ x] I have updated the documentation accordingly.
- [x ] I have updated the OpenAPI spec
https://pagopa.atlassian.net/browse/PM-1259
> PM-1259 Fix reqRef Num vpos

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/constant/ApiPaths.java
- src/main/java/it/pagopa/pm/gateway/constant/VposConstant.java
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep1ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep2ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VPosRequestUtilsTest.java
Created a new API `request-payments/creditCard/{requestId}/Step2`
Created logic to resume step2
Updated logic to resume step1
Updated Api-Spec
Updated Unit-Test
https://pagopa.atlassian.net/browse/PM-1227
> PM-1227 Step2

- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
> PM-1257 Fix unit tests

- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
Fixed table population
(https://pagopa.atlassian.net/browse/PM-1284)
> PM-1284 Fixed table population

- src/main/java/it/pagopa/pm/gateway/client/ecommerce/EcommerceClient.java
- src/main/resources/application.properties
New Api Key management for transaction's PATCH + more specific log
https://pagopa.atlassian.net/browse/PM-1247
> PM-1247 New Api Key management for transaction's PATCH + more specific log

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/constant/ApiPaths.java
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
Updated Vpos Enpoint from` ../request-payments/creditCard/..` to `../request-payments/vpos/..`
https://pagopa.atlassian.net/browse/PM-1280
> PM-1280 Updated Endpoint from creditCard to Vpos

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
Changed HttpStatus From 302 to 200 resume/method
https://pagopa.atlassian.net/browse/PM-1281
> PM-1281 Changed HttpStatus From 302 to 200 resume/method

- .env.local
- src/main/java/it/pagopa/pm/gateway/dto/ClientConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/PaymentMethodConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/CcPaymentInfoResponse.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/ClientsConfigService.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/ClientsConfig.java
- src/main/resources/application.properties
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
ClientReturnUrl management for VPos
https://pagopa.atlassian.net/browse/PM-1282
> PM-1282 ClientReturnUrl management for VPos

- .env.local
- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/utils/ClientsConfig.java
> PM-1282 Api Spec updated

- src/main/java/it/pagopa/pm/gateway/constant/VposConstant.java
- src/main/java/it/pagopa/pm/gateway/dto/enums/RefundOutcome.java
- src/main/java/it/pagopa/pm/gateway/dto/enums/VPosResponseEnum.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/Header.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/PanAliasData.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/VposDeleteResponse.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/VposOrderStatus.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/VposOrderStatusResponse.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosResponseUtils.java
PR for imports from [PM]
**old PR**: https://github.com/pagopa/pagopa-payment-transactions-gateway/pull/197
> PM-1228 Import from PM

- api-specs/api_spec_PGS.yaml
Refactoring ApiSpec
https://pagopa.atlassian.net/browse/PM-1294
> PM-1294 Refactoring ApiSpec

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/dto/vpos/CcPaymentInfoResponse.java
- src/main/java/it/pagopa/pm/gateway/dto/vpos/ThreeDsMethodData.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/service/CcPaymentInfoServiceTest.java
Adedd `threeDsMethodData` in response to GET `request-payments/vpos/{requestId}`
https://pagopa.atlassian.net/browse/PM-1320
> PM-1320 Changed Get response

- src/main/java/it/pagopa/pm/gateway/dto/xpay/XPayAuthRequest.java
Added validation rules to XPayAuthRequest's parameters
https://pagopa.atlassian.net/browse/PM-1327
> PM-1327 Added validation rules to XPayAuthRequest's parameters

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
Added @Valid in the controller's input
> PM-1327 Added @Valid in the controller's input

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
> PM-1327 Fix @Valid position

- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
Added CANCELLED case for VPOS' GET
https://pagopa.atlassian.net/browse/PM-1330
> PM-1330 Added CANCELLED case for VPOS' GET

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/client/ecommerce/EcommerceClient.java
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/ClientConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/PaymentMethodConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/config/BpayClientConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/config/ClientConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/config/PostepayClientConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/config/VposClientConfig.java
- src/main/java/it/pagopa/pm/gateway/dto/config/XpayClientConfig.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/ClientsConfig.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/main/resources/application.properties
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcPaymentInfoServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep1ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep2ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
VPos refactoring with ClientsConfig
https://pagopa.atlassian.net/browse/PM-1292
> PM-1292 VPos refactoring with ClientsConfig

- pom.xml
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/JwtTokenUtils.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/PostePayPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
- src/test/java/it/pagopa/pm/gateway/utils/JwtTokenUtilsTest.java
`requestId` made valid only for a certain amount of time.
Added JwtToken for vpos, xpay and postepay
https://pagopa.atlassian.net/browse/PM-929
> Pm 929 Time Validity of the requestId

- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
> PM-929 Fix Merge Problem

- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
Fixed Spring Initialization Error
> PM-1292 Fix Spring Initialization Error

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/resources/application.properties
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
XPay now uses the new json configuration saved as an environment variable and used through the ClientsConfig class.
https://pagopa.atlassian.net/browse/PM-1292
> PM-1292 XPay refactoring to use the new json configuration

- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/controller/PostePayPaymentTransactionsController.java
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/VposDeleteService.java
- src/main/java/it/pagopa/pm/gateway/service/XpayService.java
Fixed Spring Initialization
https://pagopa.atlassian.net/browse/PM-1348
> PM-1348 Fix Spring Initialization

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/xpay/XpayPersistableRequest.java
- src/main/java/it/pagopa/pm/gateway/entity/PaymentRequestEntity.java
Fields deleted from the request which is saved in the DB.
Fields to delete:
- apiKey
- pan
- scadenza
- cvv
- urlRisposta
- mac
https://pagopa.atlassian.net/browse/PM-1350
> PM-1350 Fix Xpay request column

- .devops/code-review-pipelines.yml
* fix pipeline code review trigger
This PR fixes an existing bug where the code review pipeline doesn't get triggered automatically when new PRs are published against production branches.
https://pagopa.atlassian.net/browse/PM-1343
> [PM-1343] fix(ci): fix pipeline code review trigger

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
Fix clientReturnUrl composition with idTransaction rather t…
> PM-1292 - Fix clientReturnUrl composition with idTransaction rather than requestId

- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VPosRequestUtilsTest.java
Fix Vpos
ThreeDsData converted in Base64
https://pagopa.atlassian.net/browse/PM-1357
> Pm 1357 fix vpos

- src/main/java/it/pagopa/pm/gateway/dto/vpos/ThreeDsMethodData.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
> PM-1357 Refactoring Vpos

- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
> PM-1357 Refactoring

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/dto/vpos/CcPaymentInfoResponse.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/test/java/it/pagopa/pm/gateway/service/CcPaymentInfoServiceTest.java
> PM-1357 Added creq in response

- .devops/code-review-pipelines.yml
* fix code review pipeline definition
> fix(pipeline): fix code review pipeline definition

- .devops/code-review-pipelines.yml
> fix(cr): set ref pipeline branch as develop

- src/main/java/it/pagopa/pm/gateway/dto/postepay/PostePayAuthRequest.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/test/java/it/pagopa/pm/gateway/controller/CreditCardPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
> Fix Junit Test

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
Added PATCH in XPAY's async call
> PM-1359 Added PATCH in XPAY's async call

- .env.local
> fix: env for local

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/VPosRequestUtils.java
- src/main/java/it/pagopa/pm/gateway/utils/VposPatchUtils.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep1ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep2ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/VposServiceTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VposPatchUtilsTest.java
Calling Revert When patch fails - **VPOS &  XPAY**
https://pagopa.atlassian.net/browse/PM-1377
> PM-1377 Calling Revert when patch fails - VPOS-XPAY

- .devops/code-review-pipelines.yml
- removed reference to repository pagopaPaymentTransactionGateway
- added pr to develop
- commented Sonar
run pipeline from develop branch
https://dev.azure.com/sia-dds/PaymentManager/_build/results?buildId=42502&view=results
https://pagopa.atlassian.net/browse/PM-1389
> Pm 1389 change subscription code review pipeline

- pom.xml
- src/main/resources/application.properties
Log root level set to "info" + logback's scope changed to "test"
> PM-1392 Log root level set to "info" + logback's scope changed to "test"

- pom.xml
> PM-1392 Reverting logback's scope change

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
Adding returnUrl to response for CANCELLED XPay payments.
> PM-1405-add-returnurl-in-xpay-ko-response

- src/main/java/it/pagopa/pm/gateway/utils/VposPatchUtils.java
> fix log message

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/utils/VposPatchUtils.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/utils/VposPatchUtilsTest.java
Removing automatic reverts for XPay and VPOS
> PM-1433 - Removing automatic reverts for XPay and VPOS

- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- remove authCode from XPAY's GET when status is not authorized
- remove method and challenge specific field from VPOS's GET when status is not created
https://pagopa.atlassian.net/browse/PM-1404
> PM-1404 pgs uniformare response

- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
Retrieve clientReturn url from vpos client config (instead of xpay) in vpos inquiry API
> Retrieve clientReturn url from vpos client config (instead of xpay)

- src/main/java/it/pagopa/pm/gateway/dto/vpos/OutcomeVposGatewayRequest.java
- src/main/java/it/pagopa/pm/gateway/dto/xpay/OutcomeXpayGatewayRequest.java
fix fill request ecommerce
https://pagopa.atlassian.net/browse/PM-1511
> PM-1511: fix fill request ecommerce

- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
deleted duplicated log info in method deleteVposPayment() of class CreditCardPaymentController
https://pagopa.atlassian.net/browse/PM-1538
> PM-1538 - deleted duplicated log info

- .devops/azure-pipelines-build-deploy-SIT.yml
- .devops/azure-pipelines-deploy-PROD.yml
- .devops/azure-pipelines-deploy-PT.yml
- .devops/azure-pipelines-deploy-UAT.yml
…in azure devops pipeline
Change azure deploy pipeline to use PublishPipelineArtifact instead of PublishBuildArtifacts
https://pagopa.atlassian.net/browse/PM-1533
> PM-1533-fix-pipeline-build-deploy

- src/main/java/it/pagopa/pm/gateway/service/VposDeleteService.java
fix for a log error message into VposDeleteService
https://pagopa.atlassian.net/browse/PM-1541
> PM-1541: fix log error message

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/service/VposService.java
- src/main/java/it/pagopa/pm/gateway/service/async/CcResumeStep1AsyncService.java
- src/main/java/it/pagopa/pm/gateway/service/async/CcResumeStep2AsyncService.java
- src/main/java/it/pagopa/pm/gateway/service/async/VposAsyncService.java
- src/main/java/it/pagopa/pm/gateway/service/async/XPayPaymentAsyncService.java
- src/main/java/it/pagopa/pm/gateway/utils/MdcUtils.java
https://github.com/pagopa/pagopa-payment-transactions-gateway/tree/PM-1549-fix-mdc-info-vpos-xpay
> Pm 1549 fix mdc info vpos xpay

- src/main/java/it/pagopa/pm/gateway/utils/JwtTokenUtils.java
fix JWT management
https://pagopa.atlassian.net/browse/PG-17
> GP-17 fix JWT management

- api-specs/api_spec_PGS.yaml
- src/main/java/it/pagopa/pm/gateway/controller/CreditCardPaymentController.java
- src/main/java/it/pagopa/pm/gateway/controller/XPayPaymentController.java
- src/main/java/it/pagopa/pm/gateway/dto/enums/PaymentRequestStatusEnum.java
- src/main/java/it/pagopa/pm/gateway/repository/PaymentRequestLockRepository.java
- src/main/java/it/pagopa/pm/gateway/service/CcPaymentInfoService.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep1Service.java
- src/main/java/it/pagopa/pm/gateway/service/CcResumeStep2Service.java
- src/main/java/it/pagopa/pm/gateway/service/async/CcResumeStep1AsyncService.java
- src/main/java/it/pagopa/pm/gateway/service/async/CcResumeStep2AsyncService.java
- src/main/java/it/pagopa/pm/gateway/service/async/XPayPaymentAsyncService.java
- src/test/java/it/pagopa/pm/gateway/beans/ValidBeans.java
- src/test/java/it/pagopa/pm/gateway/controller/XPayPaymentControllerTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcPaymentInfoServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep1ServiceTest.java
- src/test/java/it/pagopa/pm/gateway/service/CcResumeStep2ServiceTest.java
management of simultaneous calls to the resume APIs
simultaneous calls to the resume API, for the same payment, resulted in different outcomes on the VPOS side and, consequently, on the ecommerce's patch
- non regressions
- simultaneous call management
- lock management
https://pagopa.atlassian.net/browse/PG-24
> Pg 24 richiesta su pgs in stato authorized ma con patch su ecommerce ko
